env: game24

method: xot  

task:  
  data: data/game24/game24_test.csv  
  total_game_step: 3  
  task_start_index: 0  
  task_end_index: 1 
  
gpt:  
  backend: gpt-4
  temperature: 0.0  
  stop: None    
  
param:
  n_generate_sample: 1  
  n_evaluate_sample: None 
  n_select_sample: None 
  last_step: 1 
  
multi_solution: 0  
  
xot:  
  numMCTSSims: 200  
  multi_numMCTSSims: 500  
  multi_solution_exploration: 500 
  
  revised: 0  
  revise_times: 0 
  revise_total_game_step: 3  
  revise_numMCTSSims: 500  
  
model:  
  checkpoint: ./models/game24
  filename: best.pth.tar
  cpuct: 1
